name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Generate Languages Graph
      - name: Languages Graph
        uses: lowlighter/metrics@master
        with:
          filename: metrics-languages.svg # Unique filename
          token: ${{ secrets.METRICS_PROFILE_TOKEN }}
          base: "" # This removes the header/avatar to keep it clean
          plugin_languages: yes
          plugin_languages_sections: most-used

      # Step 2: Generate Achievements Graph
      - name: Achievements Graph
        uses: lowlighter/metrics@master
        with:
          filename: metrics-achievements.svg # Unique filename
          token: ${{ secrets.METRICS_PROFILE_TOKEN }}
          base: "" # Removes header
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_ignored: master, member, collaborator, organizer
